### ISSUE TITLE
test fetch_loan_page

### ISSUE THREAD

**Issue by bitboxer** [bitboxer/voebb-ical#3]
I need to find out how to test [fetch_loan_page](https://github.com/bitboxer/voebb-ical/blob/master/src/fetch_loan_page.js) .

**Comment by bitboxer** [comment]
Maybe @pmeinhardt or @weiland can explain to me how to test/mock something that uses `fetch` 🙇‍♀️ ?

**Comment by pmeinhardt** [comment]
Hi @bitboxer, I haven't had time to look at this in too much detail, but can see a number of options which — I hope — might help you get going:

1. Change your `fetchLoadPage` function to accept a `fetch` function and inject a fetch stub in your tests to provide canned responses ("dependency injection")
2. Use a different framework like Jest, which supports mocking imports/modules (see Jest [manual mocks](https://facebook.github.io/jest/docs/en/manual-mocks.html))
3. Export, then import your configured `fetch` attached to a module object so that, when mocking it in your tests, the implementation will call the mocked version, à la:
  ```javascript
  // net.js
  import fetch from 'node-fetch';
  import fetchCookie from 'fetch-cookie/node-fetch';

  export default { fetch: fetchCookie(fetch) };

  // fetch_load_page.js
  import net from './net';

  // use as…
  function loadUrl(url, cookies) {
    const res = await net.fetch(…);
    // …
  }

  // fetch_load_test.js

  const mock = sinon.mock(net);
  mock.expect('fetch').…
  ```
4. Make the base URL configurable (e.g. as a parameter), start a local server in your tests to connect to (a bit heavy maybe)
5. …

This is just a quick dump of my initial thoughts. I haven't used `Mocha` and `Sinon` too much, so the above examples might need some tweaking, but they should convey the overall idea.

Hope this actually gets you somewhere. If you need some more pointers, feel free to reach out!

Cheers :slightly_smiling_face: :wave:

**Comment by bitboxer** [comment]
Oh, so many good options. Thanks! Will have to think what I prefer. Currently leaning to do 1.

![Thank you](https://media.giphy.com/media/3ohzdQoCngNoESFV28/giphy.gif)
